# Generated by Django 4.2 on 2023-04-28 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MigracionColombia',
            fields=[
                ('index', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('ANIO', models.IntegerField(default=0)),
                ('MES', models.CharField(default='', max_length=20)),
                ('NACIONALIDAD', models.CharField(default='', max_length=50)),
                ('ISO_3166', models.IntegerField(null=True)),
                ('FEMENINO', models.IntegerField(null=True)),
                ('MASCULINO', models.IntegerField(null=True)),
                ('INDEFINIDO', models.CharField(max_length=10, null=True)),
                ('TOTAL', models.IntegerField(null=True)),
                ('LATITUD_LONGITUD', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
